services:

  postgres:

    image: postgres:15

    container_name: eka-postgres

    restart: always

    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:

    build:
      context: ./backend

    container_name: eka-backend

    restart: always

    depends_on:
      postgres:
        condition: service_started

    env_file:
      - ./backend/.env.docker

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app
    

volumes:

  postgres_data: